---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  hostnames: ['grafana.{{ env }}.{{ domain }}']
  parentRefs:
    - name: contour
      namespace: projectcontour
      sectionName: internal-https
  rules:
    - backendRefs:
        - name: grafana
          port: 80
