---
# pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
  namespace: seedbox
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-nfs