---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slow-nfs
  namespace: seedbox
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow-nfs
