---
# prepare lxc controller
- hosts: controller
  remote_user: root
  roles:
    - role: prereq
      tags: [prereq]

# set hostnames and install common packages 
- hosts: all
  become: true
  roles:
    - role: common
      tags: [common]

# nfs-server
- hosts: fast_nfs
  become: true
  roles:
    - role: nfs-server
      tags: [nfs-server]

# k0s cluster
- hosts: k0s
  become: true
  roles:
    - role: k0s
      tags: [k0s]

# infrastructure
- hosts: controller
  roles:
    - role: infrastructure
      tags: [infra]

# monitoring
- hosts: controller
  roles:
    - role: monitoring
      tags: [monitoring]

# apps
- hosts: controller
  roles:
    - role: apps/vaultwarden
      tags: [vaultwarden, vw]
