---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: contour
  namespace: projectcontour
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  gatewayClassName: contour
  listeners:
    # internal
    - name: internal-https
      hostname: '*.{{ env }}.{{ domain }}'
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: '{{ env }}.{{ domain }}'
      allowedRoutes:
        namespaces:
          from: All
    # external
    - name: external-https
      hostname: '*.{{ domain }}'
      port: 444
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: '{{ domain }}'
      allowedRoutes:
        namespaces:
          from: All
