---
# add jetstack repository
- name: add jetstack helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

# install cert-manager
- name: install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    update_repo_cache: true
    create_namespace: true
    release_namespace: cert-manager
    wait: true
    values:
      crds:
        enabled: true
      extraArgs: [--enable-gateway-api]
      config:
        apiVersion: controller.config.cert-manager.io/v1alpha1
        kind: ControllerConfiguration
        featureGates:
          ExperimentalGatewayAPISupport: true

# create cloudflare-token secret and cluster-issuer
- name: create cloudflare secret and letsencrypt cluster-issuer
  kubernetes.core.k8s:
    state: present
    template:
      - path: cert-manager/cloudflare-secret.yml
      - path: cert-manager/cloudflare-issuer.yml
