---
# nfs-provisioner
- include_tasks:
    file: nfs-provisioner.yml

# metallb
- include_tasks:
    file: metallb.yml

# cert-manager
- include_tasks:
    file: cert-manager.yml

# contour
- include_tasks:
    file: contour.yml

# wirguard
- include_tasks:
    file: wireguard.yml

# cloudflare ddns
- include_tasks:
    file: ddns.yml
