---
- set_fact:
    metallb_state: "{{ (load_balancer == 'metallb') | ternary('present', 'absent') }}"

# metallb repo
- name: add metallb helm repository
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

# metallb chart
- name: manage metallb chart
  kubernetes.core.helm:
    name: metallb
    state: '{{ metallb_state }}'
    chart_ref: metallb/metallb
    namespace: metallb-system
    wait: true
    update_repo_cache: true
    create_namespace: true

# ip pool / advertisement
- name: manage ip pool
  kubernetes.core.k8s:
    state: '{{ metallb_state }}'
    template:
      - path: ip-pool.yml
      - path: advertisement.yml
