---
- set_fact:
    fast_nfs_host: '{{ env }}-fast-nfs'

# repo 
- name: add nfs-subdir helm repo
  kubernetes.core.helm_repository:
    name: nfs-subdir-external-provisioner
    repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

# fast-nfs provisioner
- name: deploy fast-nfs provisioner
  kubernetes.core.helm:
    name: fast-nfs
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: nfs
    create_namespace: true
    values:
      nfs:
        server: "{{ hostvars[fast_nfs_host]['ansible_host'] }}"
        path: '{{ fast_nfs_export }}'
      storageClass:
        name: fast-nfs
        provisionerName: fast-nfs
        onDelete: retain
        pathPattern: ${.PVC.name}

# slow-nfs provisioner
- name: deploy slow-nfs provisioner
  kubernetes.core.helm:
    name: slow-nfs
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: nfs
    create_namespace: true
    values:
      nfs:
        server: "{{ hostvars[groups['slow_nfs'][0]]['ansible_host'] }}"
        path: '{{ slow_nfs_export }}'
      storageClass:
        name: slow-nfs
        provisionerName: slow-nfs
        onDelete: retain
        pathPattern: medias
