---
# download binary
- name: download k0s
  ansible.builtin.get_url:
    url: '{{ k0s_download_url }}/{{ k0s_version }}/k0s-{{ k0s_version }}-amd64'
    dest: /usr/bin/k0s
    mode: '0755'
    owner: '{{ username }}'
    group: '{{ username }}'

# create config directory
- name: create k0s config dir
  ansible.builtin.file:
    path: '{{ k0s_config_dir }}'
    state: directory

# controller tasks
- ansible.builtin.include_tasks:
    file: controller.yml
  when: ansible_hostname in groups['controller']

# workers tasks
- ansible.builtin.include_tasks:
    file: worker.yml
  when: ansible_hostname in groups['worker']
