---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-env
  namespace: wireguard
data:
  PUID: '{{ uid }}'
  PGID: '{{ uid }}'
  TZ: '{{ timezone }}'
  SERVERURL: wireguard.{{ domain }}
  SERVERPORT: '51820'
  PEERS: laptop,phone1,phone2,server
  PEERDNS: 192.168.21.168,1.1.1.1
  INTERNAL_SUBNET: 10.13.13.0
  ALLOWEDIPS: 0.0.0.0/0
  LOG_CONFS: 'true'
