---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.{{ vlan_id }}.41
spec:
  ports:
    - port: 51820
      protocol: UDP
      targetPort: wireguard
  selector:
    app: wireguard
  type: LoadBalancer

