---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: seedbox
spec:
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr
          ports:
            - containerPort: 9696
              name: http
          volumeMounts:
            - mountPath: /config
              name: fast-nfs
            - mountPath: /slow-nfs
              name: slow-nfs
          envFrom:
            - configMapRef:
                name: common-env
      volumes:
        - name: fast-nfs
          persistentVolumeClaim:
            claimName: prowlarr
        - name: slow-nfs
          persistentVolumeClaim:
            claimName: slow-nfs

