---
apiVersion: v1
stringData:
  domain: '{{ domain | b64encode }}'
  uid: '{{ uid | b64encode }}'
  email: '{{ email | b64encode }}'
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
type: Opaque
