---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: default
spec:
  schedule: 0 * * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: ghcr.io/logik-dev/cloudflare-ddns
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: cloudflare-ddns
          restartPolicy: Never
