---
kind: Secret
apiVersion: v1
metadata:
  name: cloudflare-ddns
  namespace: default
type: Opaque
data:
  CF_EMAIL: '{{ email | b64encode }}'
  CF_TOKEN: '{{ cloudflare_token | b64encode }}'
  CF_DOMAIN: '{{ domain | b64encode }}'
