---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: '{{ email }}'
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsNames: ['*.{{ domain }}', '*.{{ env }}.{{ domain }}']
        dns01:
          cloudflare:
            email: '{{ email }}'
            apiTokenSecretRef:
              name: cloudflare-token
              key: token
