# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: seedbox
spec:
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr
          imagePullPolicy: Always
          ports:
            - containerPort: 8989
              name: http
          volumeMounts:
            - mountPath: /config
              name: fast-nfs
            - mountPath: /slow-nfs
              name: slow-nfs
          envFrom:
            - configMapRef:
                name: common-env
      volumes:
        - name: fast-nfs
          persistentVolumeClaim:
            claimName: sonarr
        - name: slow-nfs
          persistentVolumeClaim:
            claimName: slow-nfs