---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  hostnames: ['nextcloud.{{ env }}.{{ domain }}', 'nextcloud.{{ domain }}']
  parentRefs:
    - name: contour
      namespace: projectcontour
      sectionName: internal-https
    - name: contour
      namespace: projectcontour
      sectionName: external-https
  rules:
    - backendRefs:
        - name: nextcloud
          port: 80
