---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: torrent
  namespace: seedbox
spec:
  hostnames: ['torrent.{{ env }}.{{ domain }}']
  parentRefs:
    - name: contour
      namespace: projectcontour
      sectionName: internal-https
  rules:
    - backendRefs:
        - name: torrent
          port: 80
