---
# gluetun pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun
  namespace: seedbox
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-nfs