---
# vaultwarden
- name: Deploy vaultwarden
  kubernetes.core.k8s:
    state: present
    template:
      - path: namespace.yml
      - path: pvc.yml
      - path: deployment.yml
      - path: service.yml
      - path: http-route.yml

